------------------------
class_diagram.png

@startuml
Routine "1" o-- "many"  Exercise
Routine "1" o-- "many"  Break

class Routine {
	-String description
	-String image
	-String name
	+void delete()
	+string get_description()
	+string get_image()
	+string get_name()
}

class Exercise {
	-String description
	-String image
	-Integer length
	-String name
	+void delete()
	+string get_description()
	+string get_image()
	+int get_length()
	+string get_name()
}

class Break {
	-Integer length
	+void delete()
	+int get_length()
}
@enduml

PlantUML version 1.2019.11(Sun Sep 22 10:02:15 UTC 2019)
(GPL source distribution)
Java Runtime: Java(TM) SE Runtime Environment
JVM: Java HotSpot(TM) 64-Bit Server VM
Java Version: 1.7.0_25-b15
Operating System: Linux
Default Encoding: UTF-8
Language: en
Country: US

------------------------
