------------------------
sequence_diagram.png

@startuml
actor User
control ShowButton
control DeleteButton
control Client
control Server
database Fitness
entity Workout
entity Exercise
entity ExerciseToWorkout

User -> ShowButton : click
User -> DeleteButton : click
ShowButton -> Client : request getting items
DeleteButton -> Client : request deleting items
Client -> Server : send get or delete message
Server -> Fitness : request get or delete items
Fitness -> Workout : get or delete items
Fitness -> Exercise : get or delete items
Fitness -> ExerciseToWorkout : get or delete items
Server -> Client : give items or delete message
Client -> ShowButton : give items
Client -> DeleteButton : give delete message
ShowButton -> User : show items
DeleteButton -> User : show delete message
@enduml

PlantUML version 1.2019.12(Sun Nov 03 10:24:54 UTC 2019)
(GPL source distribution)
Java Runtime: Java(TM) SE Runtime Environment
JVM: Java HotSpot(TM) 64-Bit Server VM
Java Version: 1.7.0_25-b15
Operating System: Linux
Default Encoding: UTF-8
Language: en
Country: US

------------------------
